### ISSUE TITLE
new features in Monolog ConfigResolver

### ISSUE THREAD

**Issue by kamilsk** [kamilsk/Common#20]
Inspired by
- https://github.com/theorchard/monolog-cascade
- https://github.com/Seldaek/monolog/blob/master/doc/01-usage.md

``` yml
monolog:
  loggers:
    channelX:
      handlers: [handlerA, handlerB]
      processors: [processorF]
    channelY:
      handlers: [handlerC]
```

If loggers omitted, then all handlers and processors attached to default logger.

``` yml
monolog:
  handlers:
    handlerA:
      ...config
      formatters:
      - { ...config }
    - { ...config, formatters: [formatterK] }
```

Unnamed handlers attached to all channels.

``` yml
monolog:
  processors:
    processorF:
      ...config
    - { ...config }
```

Unnamed processors attached to all handlers.

**Comment by kamilsk** [comment]
Finally:

``` yml
monolog:
  default_channel: logger
  channels:
    db:
      name: logger
      handlers:
      - info
      processors:
      - memory
    service:
      id: logger
      handlers:
      - type: chrome_php
        arguments: [info, true]
        formatter: chrome
      - id: info
        formatter: { type: json }
        processors:
        - { type: uid, arguments: { length: 7 } }
  handlers:
    info:
      type: stream
      arguments: ["%root_dir%/app/logs/info.log", info, true]
      formatter: { type: normalizer }
  processors:
    memory:
      type: memory_peak_usage
  formatters:
    chrome:
      type: chrome_php
```
