### ISSUE TITLE
add support @id in monolog/service/locator

### ISSUE THREAD

**Issue by kamilsk** [kamilsk/Common#51]
``` yaml
    queries:
      type: buffer
      arguments: ["@handler.chrome", 0, info]
```
